eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname : localhost


microservice:
    payment-service:
        endpoints:
            endpoint:
                uri:http://localhost:8765/payment/test